show databases;
create database office;
use office;
 CREATE TABLE employee
 (id INT, name STRING, dept STRING, yoj INT, salary INT)
 ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
 TBLPROPERTIES ("skip.header.line.count"="1");	
 
  LOAD DATA LOCAL INPATH '/root/empData.csv' into table employee;
  
  
  
  insert overwrite directory '/user/linoy/HiveOutput'
  row format delimited fields terminated by ','
  select * from employee where dept='IT';